# Generated by Django 4.1.2 on 2023-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Department'),
        ),
        migrations.AlterField(
            model_name='press_release',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/announcement'),
        ),
        migrations.AlterField(
            model_name='principal_desk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/announcement'),
        ),
        migrations.AlterField(
            model_name='spotlight_staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/spstaff'),
        ),
        migrations.AlterField(
            model_name='spotlight_students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/spstudents'),
        ),
    ]
