# Generated by Django 4.1.2 on 2023-04-30 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_department_image_alter_press_release_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
