# Generated by Django 4.1.2 on 2023-04-30 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='press_release',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='principal_desk',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
