# Generated by Django 4.1.2 on 2023-04-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_announcement_created_on_press_release_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlight_students',
            name='detail',
        ),
        migrations.AddField(
            model_name='spotlight_students',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight_students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/spotlight'),
        ),
    ]
