# Generated by Django 4.1.2 on 2023-04-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_spotlight_students_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/spotlight')),
                ('category', models.TextField(blank=True, null=True)),
                ('homepage', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='spotlight_students',
            old_name='category',
            new_name='detail',
        ),
        migrations.AlterField(
            model_name='spotlight_students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/spstudents'),
        ),
    ]
