# Generated by Django 4.1.2 on 2023-05-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_spotlight_rename_category_spotlight_students_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='press_release',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
