# Generated by Django 4.1.2 on 2023-05-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_press_release_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecturerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/Department')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
    ]
