# Generated by Django 4.1.2 on 2023-05-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_lecturerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturerimage',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
