# Generated by Django 4.1.2 on 2023-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_lecturerimage_name_lecturerimage_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_department_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Department')),
                ('text1', models.CharField(blank=True, max_length=100, null=True)),
                ('text2', models.CharField(blank=True, max_length=100, null=True)),
                ('text3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
