# Generated by Django 4.1.2 on 2023-05-12 21:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_main_department_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=tinymce.models.HTMLField(),
        ),
    ]
