# Generated by Django 4.1.2 on 2023-05-12 21:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_news_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
