# Generated by Django 4.2.3 on 2023-08-30 14:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_program_category_alter_program_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='principal_desk',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='category',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight_students',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
