# Generated by Django 4.2.3 on 2023-08-30 15:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_announcement_detail_alter_department_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='programBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', tinymce.models.HTMLField(blank=True)),
            ],
        ),
    ]
