# Generated by Django 4.2.3 on 2023-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_calender_researchdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchdocument',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
