# Generated by Django 4.2.3 on 2023-08-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_campus_emblem_history_principal_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purposetype',
            name='name',
        ),
    ]
