# Generated by Django 4.2.3 on 2023-09-08 23:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_srcabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrcBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, null=True)),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='SrcExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/srcCarousel')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
