# Generated by Django 4.2.3 on 2023-09-09 01:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_accomodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomodationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/srcCarousel')),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
