from django.urls import path,include
from .views import (DetailedNews,detailedPrincipal,detailedSportlight,
                    maindepartment,acemedia,mainannouncement,program,research,calender,
                    SRC,accomodation,dean,STS,Guideline,
                    church,music,cultural,history,vision,facilities,anthem,
                    staff,student,principal,alumni,emblem,contact,ict,management,libraries,
                    detailedAnnouncement,detailedPress,detailedDepartment,about)

urlpatterns=[
    path('tinymce/',include('tinymce.urls')),
    path('news/<int:news_id>',DetailedNews, name='detailed-news'),
    path('pdesk/<int:principal_id>',detailedPrincipal, name='detailed-pdesk'),
    path('announcement/<int:announce_id>',detailedAnnouncement, name='detailed-announcement'),
    path('press-release/<int:press_id>',detailedPress, name='detailed-press'),
    path('department/<int:department_id>',detailedDepartment, name='detailed-department'),
    path('sportlight/<int:sportlight_id>',detailedSportlight, name='detailed-sportlight'),
    path('home/department',maindepartment, name='main-department'),
    path('acemedia',acemedia, name='acemedia'),
    path('desk',mainannouncement, name='desk'),
    path('programs',program, name='program'),
    path('research',research, name='research'),
    path('calender',calender, name='calender'),
    path('hall',accomodation, name='hall'),
    path('SRC',SRC, name='src'),
    path('STS',STS, name='sts'),
    path('dean-of-student',dean, name='dean'),
    path('freshmen',Guideline, name='freshmen'),
    path('denominations',church, name='church'),
    path('live-band',music, name='music'),
    path('cultural',cultural, name='cultural'),
    path('history',history, name='history'),
    path('vision',vision, name='vision'),
    path('facilities',facilities, name='facilities'),
    path('anthem',anthem, name='anthem'),
    path('staff',staff, name='staff'),
    path('student',student, name='student'),
    path('past-principals',principal, name='past'),
    path('about',about, name='about'),
    path('alumni',alumni, name='alumni'),
    path('anthem',anthem, name='anthem'),
    path('logo',emblem, name='emblem'),
    path('contact',contact, name='contact'),
    path('libraries',libraries, name='libraries'),
    path('ict-service',ict, name='ict'),
    path('management',management, name='management'),



]